# Generated by Django 4.1 on 2022-08-30 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 30, 13, 33, 11, 892299), null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentor.mentor')),
            ],
        ),
    ]
