# Generated by Django 4.1 on 2022-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_month_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='fourth_month_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='second_month_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='third_month_paid',
            field=models.IntegerField(default=0),
        ),
    ]
