# Generated by Django 4.1 on 2022-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='quantity_of_classes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
