# Generated by Django 4.1 on 2022-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursetype_alter_course_description_and_more'),
        ('students', '0002_remove_student_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='course.course'),
        ),
    ]
