# Generated by Django 4.1 on 2022-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='quantiy_of_classes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
