# Generated by Django 4.1 on 2022-08-08 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor', '0002_mentor_phone_alter_mentor_quantiy_of_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2022, 8, 8, 11, 54, 1, 853944), null=True)),
                ('quantity_of_classes', models.DateField()),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentor.mentor')),
            ],
        ),
    ]
