# Generated by Django 4.1 on 2022-08-15 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classquantity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classquantity',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 15, 13, 14, 19, 91995), null=True),
        ),
    ]
