# Generated by Django 4.1 on 2022-08-08 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classquantity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classquantity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 8, 11, 55, 16, 52179), null=True),
        ),
    ]
