# Generated by Django 4.1 on 2022-08-08 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classquantity', '0003_alter_classquantity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classquantity',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 8, 11, 57, 2, 423555), null=True),
        ),
    ]
