# Generated by Django 4.1 on 2022-08-08 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classquantity', '0005_alter_classquantity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classquantity',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 8, 15, 14, 55, 928689), null=True),
        ),
        migrations.AlterField(
            model_name='classquantity',
            name='quantity_of_classes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
