# Generated by Django 4.1 on 2022-09-27 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursetype_alter_course_description_and_more'),
        ('students', '0002_remove_student_paid_and_more'),
        ('classquantity', '0007_alter_classquantity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('quantity_of_classes', models.IntegerField(blank=True, default=0, null=True)),
                ('visit', models.IntegerField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
