# Generated by Django 4.1 on 2022-10-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classquantity', '0008_studentclassquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassquantity',
            name='visit',
        ),
    ]
