# Generated by Django 4.1 on 2022-09-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='email',
        ),
        migrations.AddField(
            model_name='subadmin',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='work_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
